<a href="https://colab.research.google.com/github/emersonmrd/deep_learning_for_computer_vision/blob/main/tensorflowbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
import tensorflow as tf

In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([2, 0.0, -3], dtype=tf.float32)

casted_tensor_onde_d = tf.cast(tensor_one_d, dtype=tf.int32)
print(tensor_one_d)
print(casted_tensor_onde_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2, 0.0, -3], dtype=tf.float32)

casted_tensor_onde_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_onde_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [7]:
tensor_bool = tf.constant([True, False, False], dtype=tf.bool)
print(tensor_bool)
casted_tensor_tensor_bool = tf.cast(tensor_bool, dtype=tf.int32)
print(casted_tensor_tensor_bool)

tf.Tensor([ True False False], shape=(3,), dtype=bool)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)


In [8]:
tensor_string = tf.constant(["Hello World", "hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'hi'], shape=(2,), dtype=string)


In [9]:
tensor_one_d = tf.constant([2, 0, -3,8,90], dtype=tf.float64)
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float64)


In [10]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [11]:
tensor_three_d = tf.constant([

[[1,2,0],
[3,5,-1]],

[[10,2,0],
 [1,0,2]],

[[5,8,0],
 [2,7,0]],

[[2,1,9],
[4,-3,32]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [12]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(5,)
(4, 3)
(4, 2, 3)


In [13]:
print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)

0
1
2
3


In [14]:
tensor_four_d = tf.constant(
[
[[[1,2,0],
[3,5,-1]],

[[10,2,0],
 [1,0,2]],

[[5,8,0],
 [2,7,0]],

[[2,1,9],
[4,-3,32]]],

[[[1,2,0],
[3,5,-1]],

[[10,2,0],
 [1,0,2]],

[[5,8,0],
 [2,7,0]],

[[2,1,9],
[4,-3,32]]],


[[[1,2,0],
[3,5,-1]],

[[39,21,73],
 [49,15,2]],

[[2,9,1],
 [0,1,3]],

[[2,1,4],
[3,-1,36]]]

]
)

print(tensor_four_d.ndim)
print(tensor_four_d.shape)

4
(3, 4, 2, 3)


In [15]:
import numpy as np

In [16]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [17]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [18]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [19]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [20]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [21]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [22]:
fill_tensor = tf.fill(
    [1,3,4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [23]:
ones_tensor = tf.ones(
    [5,3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [24]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [25]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [26]:
zeros_like_tensor = tf.zeros_like(fill_tensor)
print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(1, 3, 4), dtype=int32)


In [27]:
t = tf.constant([
    [[1,1,1],
     [2,2,2]],

     [[3,3,3],
      [4,4,4]]
    ])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [28]:
t = tf.constant(
    [[1,1,1],
     [2,2,2]]
)
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [29]:
t = tf.constant([
    [[1,1,1],
     [2,2,2]],

     [[3,3,3],
      [4,4,4]]
    ])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [30]:
t = tf.constant(
    [[1,1,1],
     [2,2,2]]
    )
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [31]:
t = tf.constant(
    [[1,1,1],
     [2,2,2]]
    )
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [32]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 99.82455   98.931946]
 [ 99.70729  100.55144 ]
 [ 99.720276  99.65202 ]], shape=(3, 2), dtype=float32)


In [33]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[372 447 528 886 776]
 [  2 803 162 778 713]
 [ 27 958 291 662 172]
 [145 483 588 467 847]
 [ 36 786 260 511 259]], shape=(5, 5), dtype=int32)


In [34]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))


tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [35]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=10))


tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [36]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=1))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=1))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=1))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=1))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32, seed=1))


tf.Tensor([4 1 3], shape=(3,), dtype=int32)
tf.Tensor([4 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)
tf.Tensor([0 4 1], shape=(3,), dtype=int32)
tf.Tensor([0 1 4], shape=(3,), dtype=int32)


In [37]:
tesnor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tesnor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [38]:
tesnor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tesnor_indexed[0:4])
print(tesnor_indexed[0:6])
print(tesnor_indexed[1:6])
print(tesnor_indexed[1:6:2])
print(tesnor_indexed[:6])
print(tesnor_indexed[:])
print(tesnor_indexed[3:])
print(tesnor_indexed[1:])
print(tesnor_indexed[1:-2])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66  7], shape=(6,), dtype=int32)
tf.Tensor([6 2 4 6], shape=(4,), dtype=int32)


In [39]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [40]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d[ :3, :2])
print()
print(tensor_two_d[ :3, :])
print()
print(tensor_two_d[ 2, :])
print()
print(tensor_two_d[ 2, :1])
print()
print(tensor_two_d[ 2, 0])
print()
print(tensor_two_d[ 2, 1:])
print()
print(tensor_two_d[ :, :1])
print()
print(tensor_two_d[ :, 0])
print()
print(tensor_two_d[..., 0])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)

tf.Tensor([1 5 6], shape=(3,), dtype=int32)

tf.Tensor([1], shape=(1,), dtype=int32)

tf.Tensor(1, shape=(), dtype=int32)

tf.Tensor([5 6], shape=(2,), dtype=int32)

tf.Tensor(
[[1]
 [3]
 [1]
 [2]], shape=(4, 1), dtype=int32)

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [41]:
tensor_three_d = tf.constant([

[[1,2,0],
[3,5,-1]],

[[10,2,0],
 [1,0,2]],

[[5,8,0],
 [2,7,0]],

[[2,1,9],
[4,-3,32]]

])
print(tensor_three_d[ 1, : , :])
print()
print(tensor_three_d[ 0, 0 , :])
print()
print(tensor_three_d[ 0, : , -1])
print()
print(tensor_three_d[ 0, : , 2])
print()
print(tensor_three_d[ 0:2, : , 2])
print()
print(tensor_three_d[ ..., : , 2])
print()
print(tensor_three_d[ :, ... , 2])

tf.Tensor(
[[10  2  0]
 [ 1  0  2]], shape=(2, 3), dtype=int32)

tf.Tensor([1 2 0], shape=(3,), dtype=int32)

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)

tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [42]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [43]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [44]:
tf.sqrt((-2.25)**2 + 4.75**2 )

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [45]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.int32)
print(tf.add(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [46]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7], dtype=tf.int32) ## [7] = [7,7,7,7,7,7]
print(tf.add(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)
tf.Tensor([35 21 42 42 28 42], shape=(6,), dtype=int32)
tf.Tensor([-2 -4 -1 -1 -3 -1], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286], shape=(6,), dtype=float64)
tf.Tensor([0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286], shape=(6,), dtype=float64)


In [47]:
x_1 = tf.constant([[5,3,6,6,4,6], [5,45,65,5,53,4]], dtype=tf.int32)
x_2 = tf.constant([7], dtype=tf.int32) ## [7] = [7,7,7,7,7,7]
x_2_stretched = tf.constant([7,7,7,7,7,7])
print(tf.add(x_1,x_2))
print(tf.add(x_1,x_2_stretched))
print(tf.multiply(x_1,x_2))
print(tf.multiply(x_1,x_2_stretched))
print(tf.subtract(x_1,x_2))
print(tf.subtract(x_1,x_2_stretched))
print(tf.divide(x_1,x_2))
print(tf.divide(x_1,x_2_stretched))
print(tf.math.divide_no_nan(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2_stretched))

tf.Tensor(
[[12 10 13 13 11 13]
 [12 52 72 12 60 11]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[12 10 13 13 11 13]
 [12 52 72 12 60 11]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[ 35  21  42  42  28  42]
 [ 35 315 455  35 371  28]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[ 35  21  42  42  28  42]
 [ 35 315 455  35 371  28]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[-2 -4 -1 -1 -3 -1]
 [-2 38 58 -2 46 -3]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[-2 -4 -1 -1 -3 -1]
 [-2 38 58 -2 46 -3]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286]
 [0.71428571 6.42857143 9.28571429 0.71428571 7.57142857 0.57142857]], shape=(2, 6), dtype=float64)
tf.Tensor(
[[0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286]
 [0.71428571 6.42857143 9.28571429 0.71428571 7.57142857 0.57142857]], shape=(2, 6), dtype=float64)
tf.Tensor(
[[0.71428571 0.42857143 0.85714286 0.85714286 0.57142857 0.85714286]
 [0.71428571 6.42857143 9.28571429 0.7142857

In [48]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype=tf.int32)
x_2 = tf.constant([[7], [5], [3]], dtype=tf.int32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [49]:
x_argmax = tf.constant([[2,20,30,3,6],
                       [3,11,16,1,8],
                       [14,45,23,5,27]])

print(x_argmax.shape)

(3, 5)


In [50]:
x_argmax = tf.constant([2,20,30,3,6])

print(tf.math.argmax(x_argmax))

tf.Tensor(2, shape=(), dtype=int64)


In [51]:
x_argmax = tf.constant([200,20,30,3,6])

print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [52]:
x_argmin= tf.constant([2,20,30,3,6])

print(tf.math.argmin(x_argmin))

tf.Tensor(0, shape=(), dtype=int64)


In [53]:
x_argmin= tf.constant([2,20,30,3,1])

print(tf.math.argmin(x_argmin))

tf.Tensor(4, shape=(), dtype=int64)


In [54]:
x_argmax = tf.constant([[2,20,30,3,6],
                       [3,11,16,1,8],
                       [14,45,23,5,27]])

print(x_argmax.shape)
print(tf.math.argmax(x_argmax, axis=0)) # Column
print(tf.math.argmax(x_argmax, axis=1)) # Row

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [55]:
x_argmin = tf.constant([[2,20,30,3,6],
                       [3,11,16,1,8],
                       [14,45,23,5,27]])

print(x_argmin.shape)
print(tf.math.argmin(x_argmin, axis=0))
print(tf.math.argmin(x_argmin, axis=1))

(3, 5)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [56]:
x = tf.constant([[2,2], [3,3]])
y = tf.constant([[3,0], [1,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [57]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [58]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
] , dtype=tf.float32)


print(tf.math.reduce_sum(
    tensor_two_d, axis=None, keepdims=False, name=None
))

print(tf.math.reduce_max(
    tensor_two_d, axis=None, keepdims=False, name=None
))

print(tf.math.reduce_min(
    tensor_two_d, axis=None, keepdims=False, name=None
))

tf.Tensor(35.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(-1.0, shape=(), dtype=float32)


In [59]:
print(tf.math.reduce_sum(
    tensor_two_d, axis=0, keepdims=False, name=None
))


print(tf.math.reduce_sum(
    tensor_two_d, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_mean(
    tensor_two_d, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_std(
    tensor_two_d, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_std(
    tensor_two_d, axis=1, keepdims=True, name=None
))

tf.Tensor([ 7. 15. 13.], shape=(3,), dtype=float32)
tf.Tensor([ 3.  7. 12. 13.], shape=(4,), dtype=float32)
tf.Tensor([1.        2.3333333 4.        4.3333335], shape=(4,), dtype=float32)
tf.Tensor([0.8164966 2.4944384 2.1602468 2.6246693], shape=(4,), dtype=float32)
tf.Tensor(
[[0.8164966]
 [2.4944384]
 [2.1602468]
 [2.6246693]], shape=(4, 1), dtype=float32)


In [60]:
tf.math.top_k(tensor_two_d, k=1, sorted=True)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [61]:
x1 = tf.constant([[1,2,0],
                  [3,5,-1]])
x2 = tf.constant([[1,2,0,2],
                  [3,5,-1,2],
                  [4,5,6,2]])

print(x1, x2)
tf.linalg.matmul(
    x1,x2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False,
    output_type=None,
    name=None
)


tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 1  2  0  2]
 [ 3  5 -1  2]
 [ 4  5  6  2]], shape=(3, 4), dtype=int32)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  14]], dtype=int32)>

In [62]:
print(x1@x2)

tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  14]], shape=(2, 4), dtype=int32)


In [63]:
print(x1)
print()
print(tf.transpose(x1))

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[ 1  3]
 [ 2  5]
 [ 0 -1]], shape=(3, 2), dtype=int32)


In [64]:
print(x2)
print()
print(tf.transpose(x2))

tf.Tensor(
[[ 1  2  0  2]
 [ 3  5 -1  2]
 [ 4  5  6  2]], shape=(3, 4), dtype=int32)

tf.Tensor(
[[ 1  3  4]
 [ 2  5  5]
 [ 0 -1  6]
 [ 2  2  2]], shape=(4, 3), dtype=int32)


In [65]:
x1 = tf.constant([[1,2,0],
                  [3,5,-1]])
x2 = tf.constant([[1,2,0,2],
                  [3,5,-1,2],
                  [4,5,6,2]])
x3 = tf.constant([[1,3,4,7],
                  [5,9,7,8]])


print(x1.shape, x2.shape, x3.shape, tf.transpose(x3).shape )
print()
tf.linalg.matmul(
    x2,x3, transpose_a=False, transpose_b=True, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False,
    output_type=None,
    name=None
)


(2, 3) (3, 4) (2, 4) (4, 2)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 21,  39],
       [ 28,  69],
       [ 57, 123]], dtype=int32)>

In [66]:
x1 = tf.constant([

[[1,2],
[3,5]],

[[10,2],
 [1,0]],

[[5,0],
 [2,7]],

[[1,9],
[-3,32]]

])

x2 = tf.constant([

[[3,5,7],
[9,6,0]],

[[3,8,2],
 [7,6,1]],

[[3,2,1],
 [9,7,3]],

[[0,5,6],
[1,-3,9]]

])

print(tf.linalg.matmul(x1,x2))

tf.Tensor(
[[[  21   17    7]
  [  54   45   21]]

 [[  44   92   22]
  [   3    8    2]]

 [[  15   10    5]
  [  69   53   23]]

 [[   9  -22   87]
  [  32 -111  270]]], shape=(4, 2, 3), dtype=int32)


In [67]:
x1 = tf.constant(
[[10,2],
 [1,0]]
)

x2 = tf.constant(
[[3,8,2],
 [7,6,1]]
)

print(tf.linalg.matmul(x1,x2))

tf.Tensor(
[[44 92 22]
 [ 3  8  2]], shape=(2, 3), dtype=int32)


In [ ]:
tesnor_two_d_m_n = tf.constant([
    [0,-1,-2],
    [1,0,-1],
    [2,1,0],
    [3,2,1]
], dtype=tf.float16)

tesnor_two_d_n_m = tf.constant([
    [0,1,2],
    [-1,0,1],
    [-2,-1,0],
    [-3,-2,-1]
], dtype=tf.float16)

In [78]:
tensor_two_d = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
], dtype=tf.float32)

tensor_out_d = tf.constant([
    [1,0,0],
    [0,5,0],
    [0,0,6],
    [0,0,0]
], dtype=tf.float32)

tf.linalg.band_part(tensor_two_d, 0, 0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float32)>

In [71]:
tf.linalg.band_part(tensor_two_d, -1, 0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [72]:
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [79]:
tensor_two_d = tf.constant([
    [1,-2,0,5],
    [3,5,100,5],
    [1,5,6,5],
    [2,3,8,5]
], dtype=tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

tensor_two_d_inv

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.31023097, -0.04290427, -0.7326733 ,  1.0858085 ],
       [-0.14851484, -0.00990098,  0.13861386,  0.01980195],
       [ 0.00660066,  0.01155115,  0.00495049, -0.02310231],
       [ 0.20264027,  0.00462046,  0.2019802 , -0.20924093]],
      dtype=float32)>

In [80]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 1.0000000e+00,  1.4901161e-08,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00, -2.3841858e-07,  5.9604645e-08],
       [ 8.9406967e-08,  5.9604645e-08,  1.0000000e+00, -1.7881393e-07],
       [ 1.1920929e-07,  6.1467290e-08,  0.0000000e+00,  9.9999976e-01]],
      dtype=float32)>

In [81]:
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([100.86311     9.125967    4.563496    0.7213296], shape=(4,), dtype=float32)
tf.Tensor(
[[ 0.00204138  0.4081415  -0.8779366  -0.2502872 ]
 [ 0.9943236  -0.09612507 -0.03357515 -0.03086856]
 [ 0.06512708  0.6842663   0.47492224 -0.5495336 ]
 [ 0.08410992  0.59662384  0.0504869   0.7965028 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 0.0319082   0.21885695 -0.08825826  0.97123337]
 [ 0.05498047  0.4289185   0.90151685 -0.01653551]
 [ 0.9963603  -0.08042064 -0.02280861 -0.01668444]
 [ 0.05678995  0.8727331  -0.4230338  -0.23696883]], shape=(4, 4), dtype=float32)


In [85]:
tensor_three_d = tf.constant([

[[1,2,0],
[3,5,-1]],

[[10,2,0],
 [1,0,2]],

[[5,8,0],
 [2,7,0]],

[[2,1,9],
[4,-3,32]]

])

print(tensor_three_d.shape)
print()
print(tf.expand_dims(tensor_three_d, axis=0).shape)

(4, 2, 3)

(1, 4, 2, 3)


In [93]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis=0)
print(x_expanded.shape)
x_squeezed = tf.squeeze(x_expanded, axis=0)
print(x_squeezed.shape)

for i in range(2):
    x_squeezed = tf.squeeze(x_squeezed, axis=0)
print(x_squeezed.shape)


(1, 1, 4)
(1, 1, 1, 4)
(1, 1, 4)
(4,)


In [98]:
tensor_three_d = tf.constant([

[[1,2,0],
[3,5,-1]],

[[10,2,0],
 [1,0,2]],

[[5,8,0],
 [2,7,0]],

[[2,1,9],
[4,-3,32]]

])

print(tensor_three_d.shape)
print()
x_exp = tf.expand_dims(tensor_three_d, axis=3)
print(x_exp.shape)
print()
print(tf.squeeze(x_exp, axis= 3).shape)
print()
print(tf.reshape(x_exp, [4,2,3]).shape)

(4, 2, 3)

(4, 2, 3, 1)

(4, 2, 3)

(4, 2, 3)


In [107]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])
print(tf.reshape(x_reshape, [8,1]))
print(tf.reshape(x_reshape, [1,8]))
print(tf.reshape(x_reshape, [4,2]))
print(tf.reshape(x_reshape, [1,-1]))
print(tf.reshape(x_reshape, [-1,1]))

tf.Tensor(
[[ 3]
 [ 5]
 [ 6]
 [ 6]
 [ 4]
 [ 6]
 [-1]
 [ 2]], shape=(8, 1), dtype=int32)
tf.Tensor([[ 3  5  6  6  4  6 -1  2]], shape=(1, 8), dtype=int32)
tf.Tensor(
[[ 3  5]
 [ 6  6]
 [ 4  6]
 [-1  2]], shape=(4, 2), dtype=int32)
tf.Tensor([[ 3  5  6  6  4  6 -1  2]], shape=(1, 8), dtype=int32)
tf.Tensor(
[[ 3]
 [ 5]
 [ 6]
 [ 6]
 [ 4]
 [ 6]
 [-1]
 [ 2]], shape=(8, 1), dtype=int32)


In [110]:
t1 = [[1,2,3],[4,5,6]]
t2 = [[7,8,9],[10,11,12]]
print(tf.concat([t1,t2], axis=0))
print()
print(tf.concat([t1,t2], axis=1))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [111]:
tf.stack([t1,t2], axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [116]:
t = tf.constant([[1,2,3],
                [4,5,6]])

paddings = tf.constant([[2,5],[2,3]])
tf.pad(t, paddings, "CONSTANT", constant_values=0)

<tf.Tensor: shape=(9, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [117]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6'])
params[1:4]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [119]:
tf.gather(params, tf.range(1,4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [120]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [127]:
indices = [[0],
           [1]]

paramns = [['a', 'b'],
           ['c', 'd'],
           ['e', 'f']]

print(tf.gather_nd(paramns, indices))
print(tf.gather_nd(paramns, [0]))
print(tf.gather_nd(paramns, [2,1]))
print(tf.gather_nd(paramns, [0,0]))
print(tf.gather_nd(paramns, [2,0]))

tf.Tensor(
[[b'a' b'b']
 [b'c' b'd']], shape=(2, 2), dtype=string)
tf.Tensor([b'a' b'b'], shape=(2,), dtype=string)
tf.Tensor(b'f', shape=(), dtype=string)
tf.Tensor(b'a', shape=(), dtype=string)
tf.Tensor(b'e', shape=(), dtype=string)


In [129]:
indices = [ [0,1,0], [1,0,1] ]

params = [
    [['a0', 'b0'],
     ['c0', 'd0']],

    [['a1', 'b1'],
     ['c1', 'd1']]
]

print(tf.gather_nd(params, indices))


tf.Tensor([b'c0' b'b1'], shape=(2,), dtype=string)


In [134]:
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)

(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [135]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1,1], [3,4]],
    values=[11,56],
    dense_shape=[5,6]
)

print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [136]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [138]:
tensor_string = tf.constant(["hello", "i am", " a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b' a string'], shape=(3,), dtype=string)


In [141]:
x = tf.constant([1,2])
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [142]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [143]:
x_var.assign_add([2,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0], dtype=int32)>

In [152]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)
with tf.device('CPU:0'):
  x_tensor = tf.constant(0.2)

print(x_var.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
